name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    # https://github.com/jurplel/install-qt-action
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.12.8'
    - name: compile
      run: |
        mkdir -p build
        cmake -DIS_BUILD_GUI:BOOL=ON -S . -B build
        cd build
        make
    - name: run unit tests (gtest)
      run: |
        chmod +x ./build/test/test_main
        ./build/test/test_main