name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.12.8'
        host: ${{ matrix.os }}
    - name: Get latest CMake and Ninja
      uses: lukka/get-cmake@latest
    - name: Get Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: '15'
    - name: Compile
      run: |
        mkdir -p build
        cmake -G Ninja -DIS_BUILD_GUI:BOOL=ON -S . -B build
        cd build
        cmake --build build
    - name: run unit tests (gtest)
      run: |
        chmod +x ./build/test/test_main
        ./build/test/test_main
