name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    # https://github.com/jurplel/install-qt-action
    - name: Install Qt
    - uses: jurplel/install-qt-action@v3
      with:
        version: '5.12.8'
    - name: compile
      run: |
        chmod +x ./linux_build.sh
        sh ./linux_build.sh
